import Dexie, { type Table } from "dexie";
import { v4 as uuidv4 } from "uuid";

export interface Page {
  id?: number; // Optional because dexie generates it.
  uuid: string;
  title: string;
  order: number;
  createdAt: string;
  updatedAt: string;
}

export interface Widget {
  id?: number;
  uuid: string;
  pageId: number;
  columnId: number;
  order: number;
  title: string;
  collapsed: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Link {
  id?: number;
  uuid: string;
  widgetId: number;
  order: number;
  name: string;
  url: string;
  createdAt: string;
  updatedAt: string;
}

export class ZandarDB extends Dexie {
  pages!: Table<Page, number>;
  widgets!: Table<Widget, number>;
  links!: Table<Link, number>;
  image!: Table<Blob, string>;
  
  constructor() {
    super("ZandarDB");

    /**
     * Version 1 — initial schema
     */
    this.version(1).stores({
      pages: "++id, uuid, title, createdAt, updatedAt",
      widgets:
        "++id, uuid, pageId, columnId, order, title, collapsed, createdAt, updatedAt",
      links: "++id, uuid, widgetId, order, name, url, createdAt, updatedAt",
    });

    // version 2 - add images store
    this.version(2).stores({
      image: "",
    });

    // version 3 - pages order col
    this.version(3).stores({
      pages: "++id, uuid, title, order, createdAt, updatedAt",
    });

    this.on("populate", this.populateDefaults);
  }

  private populateDefaults = async () => {
    const now = new Date().toISOString();

    // Create default page
    const pageId = await this.pages.add({
      uuid: "c95f9bcf-2a55-4784-8a9b-637cbe8efba0",
      title: "Home",
      order: 0,
      createdAt: now,
      updatedAt: now,
    });

    // Default widgets
    // bulkAdd returns the keys(ids) generated by DB
    const [devWidgetId, socialWidgetId, vibeWidgetId ] =  await this.widgets.bulkAdd([
      {
        uuid: uuidv4(),
        title: "Developer Essentials (default)",
        pageId,
        columnId: 1,
        order: 0,
        collapsed: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        uuid: uuidv4(),
        title: "Socials (default)",
        pageId,
        columnId: 2,
        order: 0,
        collapsed: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        uuid: uuidv4(),
        title: "VibeCoding (default)",
        pageId,
        columnId: 3,
        order: 0,
        collapsed: false,
        createdAt: now,
        updatedAt: now,
      },
    ], { allKeys: true }); // https://dexie.org/docs/Table/Table.bulkAdd()

    // Default links
    await this.links.bulkAdd([
      // Links for Dev Widget
      { uuid: uuidv4(), name: "Github", url: "https://github.com", widgetId: devWidgetId, order: 0, createdAt: now, updatedAt: now },
      { uuid: uuidv4(), name: "MDN Web Docs", url: "https://developer.mozilla.org", widgetId: devWidgetId, order: 1, createdAt: now, updatedAt: now },

      // Links for Social Widget
      { uuid: uuidv4(), name: "X", url: "https://x.com", widgetId: socialWidgetId, order: 0, createdAt: now, updatedAt: now },
      { uuid: uuidv4(), name: "Reddit", url: "https://www.reddit.com/", widgetId: socialWidgetId, order: 1, createdAt: now, updatedAt: now },
      { uuid: uuidv4(), name: "Youtube", url: "https://www.youtube.com/", widgetId: socialWidgetId, order: 2, createdAt: now, updatedAt: now },

      // Links for VibeCoding Widget
      { uuid: uuidv4(), name: "ChatGPT", url: "https://chat.openai.com", widgetId: vibeWidgetId, order: 0, createdAt: now, updatedAt: now },
      { uuid: uuidv4(), name: "Claude", url: "https://claude.ai", widgetId: vibeWidgetId, order: 1, createdAt: now, updatedAt: now },
      { uuid: uuidv4(), name: "Lovable", url: "https://lovable.dev/", widgetId: vibeWidgetId, order: 2, createdAt: now, updatedAt: now },
    ]);
  }
}


export const db = new ZandarDB();

/**
 * example migration
 * db.version(2).stores({ ... }).upgrade(tx => { migrate data })
 */